export const curatedVaultHookAbi = [
  // Read functions
  {
    type: "function",
    name: "totalAssets",
    inputs: [],
    outputs: [
      { name: "amount0", type: "uint256" },
      { name: "amount1", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCurrentFee",
    inputs: [],
    outputs: [{ name: "", type: "uint24" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPerformanceMetrics",
    inputs: [],
    outputs: [
      { name: "volume", type: "uint256" },
      { name: "feeRevenue", type: "uint256" },
      { name: "swapCount", type: "uint256" },
      { name: "liquidity", type: "uint128" },
      { name: "tickLower", type: "int24" },
      { name: "tickUpper", type: "int24" },
      { name: "currentFee", type: "uint24" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "activeCuratorId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCurator",
    inputs: [{ name: "curatorId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "wallet", type: "address" },
          { name: "erc8004IdentityId", type: "uint256" },
          { name: "recommendedFee", type: "uint24" },
          { name: "performanceFeeBps", type: "uint256" },
          { name: "lastRebalanceBlock", type: "uint64" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "currentTickLower",
    inputs: [],
    outputs: [{ name: "", type: "int24" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "currentTickUpper",
    inputs: [],
    outputs: [{ name: "", type: "int24" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalLiquidity",
    inputs: [],
    outputs: [{ name: "", type: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSwaps",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cumulativeVolume",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cumulativeFeeRevenue",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "accruedPerformanceFee0",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "accruedPerformanceFee1",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vaultShares",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "poolInitialized",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "poolId",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "poolManager",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokens",
    inputs: [],
    outputs: [
      { name: "", type: "address" },
      { name: "", type: "address" },
    ],
    stateMutability: "view",
  },
  // Write functions
  {
    type: "function",
    name: "deposit",
    inputs: [
      { name: "amount0Desired", type: "uint256" },
      { name: "amount1Desired", type: "uint256" },
      { name: "amount0Min", type: "uint256" },
      { name: "amount1Min", type: "uint256" },
      { name: "minShares", type: "uint256" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [{ name: "shares", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [
      { name: "sharesToBurn", type: "uint256" },
      { name: "amount0Min", type: "uint256" },
      { name: "amount1Min", type: "uint256" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [
      { name: "amount0", type: "uint256" },
      { name: "amount1", type: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  // Events
  {
    type: "event",
    name: "Deposited",
    inputs: [
      { name: "depositor", type: "address", indexed: true },
      { name: "amount0", type: "uint256", indexed: false },
      { name: "amount1", type: "uint256", indexed: false },
      { name: "shares", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [
      { name: "withdrawer", type: "address", indexed: true },
      { name: "shares", type: "uint256", indexed: false },
      { name: "amount0", type: "uint256", indexed: false },
      { name: "amount1", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Rebalanced",
    inputs: [
      { name: "curatorId", type: "uint256", indexed: true },
      { name: "newTickLower", type: "int24", indexed: false },
      { name: "newTickUpper", type: "int24", indexed: false },
      { name: "newFee", type: "uint24", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SwapTracked",
    inputs: [
      { name: "volume", type: "uint256", indexed: false },
      { name: "feeRevenue", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "FeeUpdated",
    inputs: [
      { name: "oldFee", type: "uint24", indexed: false },
      { name: "newFee", type: "uint24", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PerformanceFeeClaimed",
    inputs: [
      { name: "curatorId", type: "uint256", indexed: true },
      { name: "wallet", type: "address", indexed: true },
      { name: "amount0", type: "uint256", indexed: false },
      { name: "amount1", type: "uint256", indexed: false },
    ],
  },
] as const;
