/**
 * logger.ts — Structured logging and payment log for Phase 4 tools.
 *
 * All logs are written as JSONL to agent/data/:
 *   - cycle.log        — general structured logs (debug, info, warn, error)
 *   - payment-log.json — on-chain payment records (Olas tx hashes, Locus txs)
 *
 * The payment-log.json file is the primary bounty proof artifact — it records
 * every on-chain tx hash generated by Olas Mech and Locus payments.
 *
 * Logs also go to stderr so OpenClaw gateway captures them.
 */

import { appendFileSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { DATA_DIR } from "./config.js";

// Ensure data dir exists
try {
  mkdirSync(DATA_DIR, { recursive: true });
} catch {
  // ignore — already exists
}

const CYCLE_LOG   = join(DATA_DIR, "cycle.log");
const PAYMENT_LOG = join(DATA_DIR, "payment-log.jsonl");

/** Structured cycle log for the frontend (JSON array format) */
const CYCLE_LOG_JSON = process.env.CYCLE_LOG_JSON_PATH
  ?? join(DATA_DIR, "../../frontend/public/cycle-log.json");

export type LogLevel = "debug" | "info" | "warn" | "error";

/**
 * Write a structured log entry to stderr + cycle.log.
 */
export function log(
  level: LogLevel,
  msg: string,
  data?: Record<string, unknown>
): void {
  const entry = {
    ts: new Date().toISOString(),
    level,
    msg,
    ...(data ?? {}),
  };
  const line = JSON.stringify(entry);
  // Always write to stderr (OpenClaw captures this)
  process.stderr.write(line + "\n");
  // Append to persistent cycle log
  try {
    appendFileSync(CYCLE_LOG, line + "\n");
  } catch {
    // non-fatal — disk write failure shouldn't crash the tool
  }
}

// ─── Structured cycle log (frontend-compatible) ─────────────────────────────

export interface CycleLogEntry {
  timestamp: string;
  action: "REBALANCED" | "SKIPPED" | "CLAIMED" | "ERROR";
  summary: string;
  venice?: { reasoning: string; confidence: number; model: string };
  rebalance?: {
    oldTickLower: number; oldTickUpper: number;
    newTickLower: number; newTickUpper: number;
    oldFee: number; newFee: number;
  };
  attestation?: string;
  txHash?: string;
  serviceCounts?: Record<string, number>;
  error?: string;
}

/**
 * Append a structured cycle entry to frontend/public/cycle-log.json.
 * The frontend's useAgentLogs() hook polls this file every 30s.
 */
export function logCycle(entry: CycleLogEntry): void {
  try {
    let entries: CycleLogEntry[] = [];
    try {
      const raw = readFileSync(CYCLE_LOG_JSON, "utf-8").trim();
      if (raw.startsWith("[")) entries = JSON.parse(raw);
    } catch {
      // file doesn't exist or is malformed — start fresh
    }
    entries.push(entry);
    // Keep last 100 entries
    if (entries.length > 100) entries = entries.slice(-100);
    writeFileSync(CYCLE_LOG_JSON, JSON.stringify(entries, null, 2));
  } catch {
    // non-fatal
  }
  log("info", `cycle: ${entry.action} — ${entry.summary}`);
}

export type PaymentSource = "olas" | "locus";

/**
 * Record an on-chain payment for bounty proof.
 * All payment records are appended to payment-log.jsonl.
 *
 * @param source      Which protocol generated this payment
 * @param txHash      On-chain transaction hash
 * @param amountUsdc  Amount paid in USDC (0 for native-token payments)
 * @param meta        Extra fields (prompt, tool, requestId, etc.)
 */
export function logPayment(
  source: PaymentSource,
  txHash: string,
  amountUsdc: number,
  meta?: Record<string, unknown>
): void {
  const entry = {
    ts: new Date().toISOString(),
    source,
    txHash,
    amountUsdc,
    ...(meta ?? {}),
  };
  try {
    appendFileSync(PAYMENT_LOG, JSON.stringify(entry) + "\n");
  } catch {
    // non-fatal
  }
  log("info", `payment logged: ${source} tx=${txHash} $${amountUsdc}`, meta);
}
