/**
 * logger.ts — Structured logging and payment log for Phase 4 tools.
 *
 * All logs are written as JSONL to agent/data/:
 *   - cycle.log        — general structured logs (debug, info, warn, error)
 *   - payment-log.json — on-chain payment records (Olas tx hashes, Locus txs)
 *
 * The payment-log.json file is the primary bounty proof artifact — it records
 * every on-chain tx hash generated by Olas Mech and Locus payments.
 *
 * Logs also go to stderr so OpenClaw gateway captures them.
 */

import { appendFileSync, mkdirSync } from "fs";
import { join } from "path";
import { DATA_DIR } from "./config.js";

// Ensure data dir exists
try {
  mkdirSync(DATA_DIR, { recursive: true });
} catch {
  // ignore — already exists
}

const CYCLE_LOG   = join(DATA_DIR, "cycle.log");
const PAYMENT_LOG = join(DATA_DIR, "payment-log.jsonl");

export type LogLevel = "debug" | "info" | "warn" | "error";

/**
 * Write a structured log entry to stderr + cycle.log.
 */
export function log(
  level: LogLevel,
  msg: string,
  data?: Record<string, unknown>
): void {
  const entry = {
    ts: new Date().toISOString(),
    level,
    msg,
    ...(data ?? {}),
  };
  const line = JSON.stringify(entry);
  // Always write to stderr (OpenClaw captures this)
  process.stderr.write(line + "\n");
  // Append to persistent cycle log
  try {
    appendFileSync(CYCLE_LOG, line + "\n");
  } catch {
    // non-fatal — disk write failure shouldn't crash the tool
  }
}

export type PaymentSource = "olas" | "locus";

/**
 * Record an on-chain payment for bounty proof.
 * All payment records are appended to payment-log.jsonl.
 *
 * @param source      Which protocol generated this payment
 * @param txHash      On-chain transaction hash
 * @param amountUsdc  Amount paid in USDC (0 for native-token payments)
 * @param meta        Extra fields (prompt, tool, requestId, etc.)
 */
export function logPayment(
  source: PaymentSource,
  txHash: string,
  amountUsdc: number,
  meta?: Record<string, unknown>
): void {
  const entry = {
    ts: new Date().toISOString(),
    source,
    txHash,
    amountUsdc,
    ...(meta ?? {}),
  };
  try {
    appendFileSync(PAYMENT_LOG, JSON.stringify(entry) + "\n");
  } catch {
    // non-fatal
  }
  log("info", `payment logged: ${source} tx=${txHash} $${amountUsdc}`, meta);
}
